---
title: "Immigration"
author: "Emmanuel Yeboah"
format: html
editor: visual
---


Questions: What will be the attitude toward immigration, measured on the 3 to 15 scale?

of a Parisian after they hear two Arabic speakers walking down the street?

What about the average Parisian? What about the 90th percentile of Parisians?

Preceptor Table is a table of data with rows and columns such that, if there is no missing data, it is easy to estimate the quantity of interest.

Unit: Parisian
outcome: the attitude toward immigration in a number.
covariates: hearing the Arabic speakers or not hearing
first columns: ID
second columns: both treatments
third: difference between the two

Population Table can be constructed if the validity assumption is (mostly) true. It includes all the rows and columns from the Preceptor Table. It also includes the rows and columns from the data set. It generally has other rows as well, rows which represent unit/time combinations from other components of the population.


Validity is the consistency, or lack there of, in the columns of our dataset and the corresponding columns in our Preceptor Table. In order to consider the two datasets to be drawn from the same population, the columns from one must be have a valid correspondence with the columns in the other. Validity, if true (or at least reasonable), allows us to construct the Population Table.





